language: node_js

notifications:
  email:
    on_success: change
    on_failure: change

node_js:
  - "0.12"
  - "iojs"

after_success:
  - 'npm run coverage && npm run sendToCoveralls'

before_script:
  - sudo ./.travis-deps.sh
