language: node_js

notifications:
  email:
    on_success: change
    on_failure: change

node_js:
  - "0.12"
  - "iojs"

after_success:
  - 'npm run coverage && npm run sendToCoveralls'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install nginx
  - sudo wget -P /usr/local/bin https://godist.herokuapp.com/projects/ddollar/forego/releases/current/linux-amd64/forego
  - sudo chmod u+x /usr/local/bin/forego
